//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-android v0.15
//
package com.amazonaws.mobile;

import com.amazonaws.regions.Regions;

/**
 * This class defines constants for the developer's resource
 * identifiers and API keys. This configuration should not
 * be shared or posted to any public source code repository.
 */
public class AWSConfiguration {
    // AWS MobileHub user agent string
    public static String AWS_MOBILEHUB_USER_AGENT;
    // AMAZON COGNITO
    public static Regions AMAZON_COGNITO_REGION;
    public static String AMAZON_COGNITO_IDENTITY_POOL_ID;
    public static Regions AMAZON_DYNAMODB_REGION;
    public static String AMAZON_COGNITO_USER_POOL_ID;
    public static String AMAZON_COGNITO_USER_POOL_CLIENT_ID;
    public static String AMAZON_COGNITO_USER_POOL_CLIENT_SECRET;

    public static void setRegionCognito(String regionName){
        AMAZON_COGNITO_REGION = Regions.fromName(regionName);
    }
    public static void setRegionDynamonDB(String regionName){
        AMAZON_DYNAMODB_REGION = Regions.fromName(regionName);
    }
}
